### ISSUE TITLE
Cant resolve module timers-browserify

### ISSUE THREAD

**Issue by EvgeniyLyakhov** [browserify/timers-browserify#27]
Hi guys,
I have problem with version 2.0.4,
`Error: Cannot find module 'timers-browserify'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.<anonymous> (/Users/evgeniylyakhov/WebstormProjects/postgame-frontend/node_modules/node-libs-browser/index.js:32:31)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/evgeniylyakhov/WebstormProjects/postgame-frontend/node_modules/webpack/lib/node/NodeSourcePlugin.js:7:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at OptionsApply.WebpackOptionsApply.process (/Users/evgeniylyakhov/WebstormProjects/postgame-frontend/node_modules/webpack/lib/WebpackOptionsApply.js:72:28)
    at webpack (/Users/evgeniylyakhov/WebstormProjects/postgame-frontend/node_modules/webpack/lib/webpack.js:22:48)
    at processOptions (/Users/evgeniylyakhov/WebstormProjects/postgame-frontend/node_modules/webpack/bin/webpack.js:152:17)
    at Object.<anonymous> (/Users/evgeniylyakhov/WebstormProjects/postgame-frontend/node_modules/webpack/bin/webpack.js:192:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)`

I checked version 2.0.2 and in version 2.0.4 in package.json I can't find 
 "main": "main.js",
Is it a cause?

**Comment by jryans** [comment]
The code in 2.0.2 vs. 2.0.4 is the same:

https://github.com/jryans/timers-browserify/compare/v2.0.2...v2.0.4

Only the contributors list and change log are different.

**Comment by bxthomas** [comment]
I can confirm I have the same problem.  2.0.4 yields the cannot find module message, 2.0.3 and before does not.

**Comment by jryans** [comment]
I'll need a clear test case with steps to reproduce the issue in order to make progress here.

2.0.4 should be identical to 2.0.2, so it's quite confusing that you see different behavior.

**Comment by jryans** [comment]
No updates provided here in a while and more info is needed to proceed. Feel free to reopen if this is still valid and you have more to add.
